### ISSUE TITLE
Have to try to launch often in order for it to connect to radio on localhost

### ISSUE THREAD

**Issue by Andy-KU7T** [K1DBO/slice-master-6000#11]
connecting to the local radio is not reliable. I have to retry often. 1 out of 5 tries gets connected to the radio and my 4 CW Skimmers launched correctly. I hope you can find out some error details from teh log below. I have included all lines that inlcude the term "error":

2018-11-22 20:51:06,154 DETAIL slice_master.main Clock is within tolerance clock_error=21
2018-11-22 20:51:07,845 ERROR  slice_master.select_radio internal error
Traceback (most recent call last):
  File "slice_master.py", line 127, in tick
  File "slice_master.py", line 474, in select_radio
  File "slice_master.py", line 196, in connect_radio
  File "site-packages\flex\flex.py", line 463, in connect
  File "site-packages\flex\flex.py", line 535, in wait_for_status
Timeout: still waiting for transmit
2018-11-22 20:51:11,365 DETAIL slice_master.logger flex.flex.Status.update.gps.freq_error
2018-11-22 20:51:11,372 DETAIL slice_master.logger flex.flex.Status.update.radio.freq_error_ppb

**Comment by K1DBO** [comment]
Hi Andy,
I just uploaded a bug fix release (v0.10.5f) that should fix this issue.  Please give it a try,

--Don
