### ISSUE TITLE
IP address connect issue

### ISSUE THREAD

**Issue by jshowelljr** [K1DBO/slice-master-6000#3]
Hi Don,  

RE:  Slice Master 6000 v0.10.1

It seems to go into a loop at startup connecting to the IP address.  Please see video here: 
https://drive.google.com/file/d/1snEyQ0MHwLj59G7aDvOXryseYZNteRqz/view?usp=sharing

I first noticed this on the previous version and thought I'd just wait for the next release and didn't report it.

Thanks,
John AF3K

**Comment by jshowelljr** [comment]
Hi Don,

Deleted the AppData\Local\K1DBO and still have the same issue.  Anything else to try?  BTW, it's a 6600M and  SmartSDR v2.1.33. 

Happy to try something else.

John

**Comment by K1DBO** [comment]
John,

Grab this version

https://www.dropbox.com/s/rrdxej0ante5sz9/slice-master-debug.exe?dl=0

and try running it from a cmd window.  It should produce output to the cmd window that will help.  A copy-n-paste from the window or even a screen shot should help.

Thanks.
--Don

**Comment by jshowelljr** [comment]
Don, Here you go....hope this helps. - John

Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\JH>cd downloads

C:\Users\JH\Downloads>slice-master-debug.exe
16:38:30 INFO  telnet.listener Listening for telnet connections. port=7300
Traceback (most recent call last):
  File "slice_master.py", line 112, in tick
  File "slice_master.py", line 449, in select_radio
  File "slice_master.py", line 175, in connect_radio
  File "site-packages\flex\flex.py", line 435, in connect
  File "site-packages\flex\flex.py", line 486, in wait_for_status
  File "site-packages\flex\flex.py", line 542, in read
  File "site-packages\flex\flex.py", line 649, in parse_status
  File "shlex.py", line 279, in split
  File "shlex.py", line 269, in next
  File "shlex.py", line 96, in get_token
  File "shlex.py", line 172, in read_token
ValueError: No closing quotation
Traceback (most recent call last):
  File "slice_master.py", line 112, in tick
  File "slice_master.py", line 449, in select_radio
  File "slice_master.py", line 175, in connect_radio
  File "site-packages\flex\flex.py", line 435, in connect
  File "site-packages\flex\flex.py", line 486, in wait_for_status
  File "site-packages\flex\flex.py", line 542, in read
  File "site-packages\flex\flex.py", line 649, in parse_status
  File "shlex.py", line 279, in split
  File "shlex.py", line 269, in next
  File "shlex.py", line 96, in get_token
  File "shlex.py", line 172, in read_token
ValueError: No closing quotation
Traceback (most recent call last):
  File "slice_master.py", line 112, in tick
  File "slice_master.py", line 449, in select_radio
  File "slice_master.py", line 175, in connect_radio
  File "site-packages\flex\flex.py", line 435, in connect
  File "site-packages\flex\flex.py", line 486, in wait_for_status
  File "site-packages\flex\flex.py", line 542, in read
  File "site-packages\flex\flex.py", line 649, in parse_status
  File "shlex.py", line 279, in split
  File "shlex.py", line 269, in next
  File "shlex.py", line 96, in get_token
  File "shlex.py", line 172, in read_token
ValueError: No closing quotation
Traceback (most recent call last):
  File "slice_master.py", line 112, in tick
  File "slice_master.py", line 449, in select_radio
  File "slice_master.py", line 175, in connect_radio
  File "site-packages\flex\flex.py", line 435, in connect
  File "site-packages\flex\flex.py", line 486, in wait_for_status
  File "site-packages\flex\flex.py", line 542, in read
  File "site-packages\flex\flex.py", line 649, in parse_status
  File "shlex.py", line 279, in split
  File "shlex.py", line 269, in next
  File "shlex.py", line 96, in get_token
  File "shlex.py", line 172, in read_token
ValueError: No closing quotation
Traceback (most recent call last):
  File "slice_master.py", line 112, in tick
  File "slice_master.py", line 449, in select_radio
  File "slice_master.py", line 175, in connect_radio
  File "site-packages\flex\flex.py", line 435, in connect
  File "site-packages\flex\flex.py", line 486, in wait_for_status
  File "site-packages\flex\flex.py", line 542, in read
  File "site-packages\flex\flex.py", line 649, in parse_status
  File "shlex.py", line 279, in split
  File "shlex.py", line 269, in next
  File "shlex.py", line 96, in get_token
  File "shlex.py", line 172, in read_token
ValueError: No closing quotation
Traceback (most recent call last):
  File "slice_master.py", line 112, in tick
  File "slice_master.py", line 449, in select_radio
  File "slice_master.py", line 175, in connect_radio
  File "site-packages\flex\flex.py", line 435, in connect
  File "site-packages\flex\flex.py", line 486, in wait_for_status
  File "site-packages\flex\flex.py", line 542, in read
  File "site-packages\flex\flex.py", line 649, in parse_status
  File "shlex.py", line 279, in split
  File "shlex.py", line 269, in next
  File "shlex.py", line 96, in get_token
  File "shlex.py", line 172, in read_token
ValueError: No closing quotation
Traceback (most recent call last):
  File "slice_master.py", line 112, in tick
  File "slice_master.py", line 449, in select_radio
  File "slice_master.py", line 175, in connect_radio
  File "site-packages\flex\flex.py", line 435, in connect
  File "site-packages\flex\flex.py", line 486, in wait_for_status
  File "site-packages\flex\flex.py", line 542, in read
  File "site-packages\flex\flex.py", line 649, in parse_status
  File "shlex.py", line 279, in split
  File "shlex.py", line 269, in next
  File "shlex.py", line 96, in get_token
  File "shlex.py", line 172, in read_token
ValueError: No closing quotation
Traceback (most recent call last):
  File "slice_master.py", line 112, in tick
  File "slice_master.py", line 449, in select_radio
  File "slice_master.py", line 175, in connect_radio
  File "site-packages\flex\flex.py", line 435, in connect
  File "site-packages\flex\flex.py", line 486, in wait_for_status
  File "site-packages\flex\flex.py", line 542, in read
  File "site-packages\flex\flex.py", line 649, in parse_status
  File "shlex.py", line 279, in split
  File "shlex.py", line 269, in next
  File "shlex.py", line 96, in get_token
  File "shlex.py", line 172, in read_token
ValueError: No closing quotation

C:\Users\JH\Downloads>

**Comment by K1DBO** [comment]
Hi John,

That does help.  You said earlier version of Slice Master worked for you.  Is there any chance you changed the "nick name" of your radio or your callsign that's stored in your radio?  

--Don

**Comment by jshowelljr** [comment]
It's possible...but not sure I remember making changes in Slice Master.  In the last few months I've upgraded from a 6500 to a 6600M,  and have also operated the 6600 under a different call (VP5P).  The PC running Slice Master has remained the same.

**Comment by K1DBO** [comment]
Perfect!  

I was on the right track.  It was a "user entered" value but not the callsign or nickname.  

You have a memory entry for FT8 that is causing Slice Master some trouble.  The mode name contains a typo.  I suspect it should say DIGU, but instead it says DIGU' (notice the trailing quote).  If you fix that typo (remove the trailing quote), all should be well.

**Comment by jshowelljr** [comment]
Don,  I noticed the same thing.  Just removed that entry and all is well!! Thanks for your help. Looking forward to using it again!! John AF3K

**Comment by K1DBO** [comment]
You're welcome John, thanks for reporting the bug.
